config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  get 'about' => 'static#about'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get '/search/:name' => 'users#search', as: 'search'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
      Microblog Labs
  </small>
  <nav>
      <ul>
          <li><%= link_to t("footer.about"), about_path %></li>
      </ul>
  </nav>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Microblog Labs", root_path, id: "logo", class: "navbar-brand" %>
          </div>

          <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                  <li>
                      <%= link_to root_path(locale: 'en') do %>
                        <%= image_tag "gb.gif" %>
                      <% end %>
                  </li>
                  <li>
                      <%= link_to root_path(locale: 'pt-BR') do %>
                        <%= image_tag "br.gif" %>
                      <% end %>
                  </li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                  <li><%= link_to t("nav.home"), root_path %></li>
                  <li><%= link_to t("nav.about"), about_path %></li>
                  <% if logged_in? %>
                    <li><%= link_to t("static.home.users"), users_path %></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <%= t("static.home.account") %> <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to t("static.home.profile"), current_user %></li>
                            <li><%= link_to t("static.home.settings"), edit_user_path(current_user) %></li>
                            <li class="divider"></li>
                            <li>
                                <%= link_to t("static.home.logout"), logout_path, method: "delete" %>
                            </li>
                        </ul>
                    </li>
                  <% else %>
                    <li><%= link_to t("nav.login"), login_path %></li>
                  <% end %>
              </ul>
              <%= render 'layouts/search' %>
          </div>
      </div>
  </nav>

app/views/layouts/_search.html.erb
<%= form_tag(users_path, method: 'get', class: 'navbar-form navbar-right',
    :role => 'search', :enforce_utf8 => false) do %>
  <div class="form-group">
    <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: t("nav.search") %>
  </div>
  <%= button_tag nil, type: 'submit', class:'btn btn-default', name: nil do %>
    <%= content_tag(:span, nil, class: 'glyphicon glyphicon-search', :'aria-hidden' => true ) %>
  <% end %>
<% end %>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= complete_title(yield(:title)) %></title>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Lobster" %>
        <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Montserrat" %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <%= render "layouts/shim" %>
    </head>
    <body>
        <%= render 'layouts/nav' %>

        <div class="container">
            <% flash.each do |message_type, message| %>
              <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
            <% end %>
            <%= yield %>
            <%= render 'layouts/footer' %>
        </div>
    </body>
</html>